// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPumpStatusChange();
void onPushButtonChange();

float read_Pot;
bool pump_status;
bool push_button;

void initProperties(){

  ArduinoCloud.addProperty(read_Pot, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(pump_status, READWRITE, ON_CHANGE, onPumpStatusChange, 1);
  ArduinoCloud.addProperty(push_button, READWRITE, ON_CHANGE, onPushButtonChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
